baseURL = "http://hackutk.org"
languageCode = "en-us"
title = "HackUTK"

discordInvite = "https://discord.gg/tukPS5PFHP"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
